### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by igzmanuelmartinvivaldi** [pawanmaurya/fetchflix.info#1]
Looks like something is failing in the last weeks, it stopped working in Windows 8.1 Chrome 41. 

It keeps forever with the message '124 video files are found in your directory. Now searching for movie info.' but no movie info is found.

The same errors happens with other folders, find the info for a few movies and then show a javascript error in the console and stops finding movies info:

There is one error in the console:
Uncaught TypeError: Cannot read property 'title' of undefinedlocal.min.js:1 
p local.min.js:1 
$.ajax.success jquery.min.js:2 
m.Callbacks.j jquery.min.js:2 
m.Callbacks.k.fireWith jquery.min.js:4 
x jquery.min.js:4 
m.ajaxTransport.send.b.onload.b.onreadystatechange

**Comment by lardissone** [comment]
+1

**Comment by igzmanuelmartinvivaldi** [comment]
Just tested in Windows 10, Chrome 51 with 82 movies and is working, so this bug could be closed.
